### PR TITLE
Add direct Sprintf support

### PR DESCRIPTION
**Pull request by erikh**
Here you go, I figure this is self-explanatory! :)

### CODE REVIEW

**Comment by fatih** [comment]
Hi @erikh 

Thanks for your contribution. Sorry for the late response as I'm busy lately. Can you add also `Sprint()` so it's the same with the other public facing API's. Thanks.

**Comment by erikh** [comment]
Yep sure! Might be a few days, moving atm.

**Comment by erikh** [comment]
Just patched it in, do you mind taking another look?

**Comment by fatih** [comment]
Thanks @erikh, looks good 👍

**Comment by erikh** [comment]
Thanks!

**Pull request merged**
