### PR TITLE
Upgrade dependency versions

### PR DESCRIPTION
**Pull request by tliron**
Specifically important is the upgrade of github.com/mattn/go-isatty, because the older v0.0.3 was broken for WASM compilation.

I know you don't want to maintain this library anymore, but it's so useful! This is a small fix, I hope you can merge and release a new version of your library! Thank you!

### CODE REVIEW

**Comment by fatih** [comment]
Sounds good, let's do it :) Can you also call please `go mod tidy` and `go mod vendor` ? We vendor the dependencies and I want to make sure it's up-to-date.

**Comment by tliron** [comment]
Done!

**Comment by fatih** [comment]
Thank you @tliron

**Comment by fatih** [comment]
Cut a new release with these changes: https://github.com/fatih/color/releases/tag/v1.9.0

**Pull request merged**
